title: Xu Zhitong
description: :)
site_title: '@ZhitongXu - Xu Zhitong'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ZhitongXu
blog_url: https://zhitongxu.github.io
email: ZhitongX@163.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 